// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkd3SmgZDiXc7Z_lZM4820MoJBNt9Haks',
    appId: '1:1056668448570:web:fd65e91da5fa8c22244203',
    messagingSenderId: '1056668448570',
    projectId: 'delicias-em-camadas',
    authDomain: 'delicias-em-camadas.firebaseapp.com',
    storageBucket: 'delicias-em-camadas.firebasestorage.app',
    measurementId: 'G-60GEQVCTD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wr66a6EslzdXJ4GPRJjPECuCLWRNKQI',
    appId: '1:1056668448570:android:e95b9f0ab5e386b0244203',
    messagingSenderId: '1056668448570',
    projectId: 'delicias-em-camadas',
    storageBucket: 'delicias-em-camadas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID:ios:YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'gerenciador-confeitaria',
    storageBucket: 'gerenciador-confeitaria.appspot.com',
    iosBundleId: 'com.gerenciador.gerenciadorConfeitaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_APP_ID:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'gerenciador-confeitaria',
    storageBucket: 'gerenciador-confeitaria.appspot.com',
    iosBundleId: 'com.gerenciador.gerenciadorConfeitaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:YOUR_APP_ID:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'gerenciador-confeitaria',
  );
}